apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myadimin-service
  name: myadimin-service
spec:
  type: NodePort
  ports:
   - nodePort: 30011
     port: 80
     protocol: TCP
     targetPort: 8080
  selector:
    app: database


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: myadmin
        image: phpmyadmin
        ports:
          - containerPort: 8080
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
      



