apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-service
  name: spring-service
spec:
  type: LoadBalancer
  ports:
   - nodePort: 30005
     port: 8081
     protocol: TCP
     targetPort: 8081
  selector:
    app: spring-service


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
      - name: demo-springapp
        image: jeewangautam02261995/springbootapp:v2
      

