kind: Cluster 
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-mulinode-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30005
    hostPort: 8081
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
